imports:
    - { resource: config.yml }
    - { resource: security_test.yml }
    - { resource: parameters_test.ini }

# security:
    # ~

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
# imports:
    # - { resource: config_dev.yml }
    # - { resource: security_test.yml }

# framework:
    # test: ~
    # session:
        # storage_id: session.storage.filesystem

# web_profiler:
    # toolbar: false
    # intercept_redirects: false

swiftmailer:
    disable_delivery: true
